%% analysis_visual_FONDUTA_FIR.m — Visual GLM Analysis: FIR Basis
%
% Companion to analysis_visual_FONDUTA_HRF.m. Replaces HRF convolution with
% a Finite Impulse Response (FIR) temporal-lag basis, allowing the data to
% estimate the hemodynamic response shape directly rather than assuming the
% SPM canonical HRF.
%
% USAGE:
%   1. Set FONDUTA_PATH below to the location of your FONDUTA directory.
%   2. Run from within ANALYSES/VISUAL/ so that Datapath.m and the local
%      +fn/ package are visible.  FONDUTA can be anywhere on disk.
%
% RUNNING FROM TERMINAL
% cd /data00/leonardo/github/fUSI_analyses/ANALYSES/VISUAL
% nohup matlab -nodisplay -nosplash -r "analysis_visual_FONDUTA_FIR; exit" > fir_analysis.log 2>&1 &
%
%
% FIR DESIGN:
%   A window of W = stim_duration + time_window_after_offset seconds is divided
%   into N = round(W / time_resampling) equally-spaced nodes/bins.
%   Each predictor that was HRF-convolved in the HRF script is replaced by a
%   block of N FIR columns generated by fn.generate_fir_basis().
%
%   stim_duration is auto-detected per session from PDI.stimInfo.
%   With defaults (time_window_after_offset=12 s, time_resampling=0.5 s)
%   and stim_duration=15 s (typical), N = 54 nodes per predictor.
%
% MODELS:
%   F1_StimOnly    : fir(stim_all)                             [T × N]
%   F2_Behavior    : [fir(stim_all), wheel_c, fir(wheel_c), fir(stim.*wheel_c)]
%                    [T × (3N+1)]  — continuous predictors pre-centred
%   F3_SteadyVisual: fir(stim_stationary) on stationary frames only [T_steady × N]
%
% F-CONTRASTS:
%   An omnibus F-test is computed for each FIR block, testing whether ANY of
%   its N betas are jointly non-zero (i.e., whether the term contributes to
%   the response at any lag).  Results are stored in .fcontrasts.<term>.
%   Partial eta² is also computed for comparison with HRF-model eta² maps.
%
% OUTPUT:
%   Saved per session as glm_<runName>_FIR.mat (variable 'data').
%   The struct is identical in structure to the HRF output and is compatible
%   with fonduta.viz.view_glm.  Each model has the standard fields:
%     .betas, .eta2, .tstat, .zstat, .R2, .Xmodel, .predictor_labels, .model_name
%   plus the FIR-specific fields:
%     .fcontrasts.<term>.Fmap    [nx × ny] — omnibus F-statistic map
%     .fcontrasts.<term>.eta2_p  [nx × ny] — partial eta² from F-test
%     .fcontrasts.<term>.df_effect / .df_error
%     .fir_params                           — FIR windowing parameters
%
% IMPORTANT — no z-scoring of FIR columns:
%   FIR basis columns consist of sparse tent/boxcar pulses with exact 0 baselines.
%   Z-scoring would shift zero-values to negatives and destroy amplitude scales.
%   skip_zscore=true is passed to fonduta.glm.ols() for all FIR models.
%
% Dependencies:
%   FONDUTA package  (set FONDUTA_PATH below)
%   Datapath.m       (in this directory — provides session paths)
%   +fn/             (in this directory):
%       fn.detect_running_trials
%       fn.build_visual_predictors
%       fn.build_wheel_signal
%       fn.generate_fir_basis   ← new for FIR

%% =========================================================================
%  CONFIGURATION — edit these parameters before running
%  =========================================================================

FONDUTA_PATH = '/data00/leonardo/github/fUSI_analyses/FONDUTA';
addpath(genpath(FONDUTA_PATH));

condition    = 'VisualTest';   % experiment condition (passed to Datapath)
resultFolder = condition;      % output subfolder name

speedThresh  = 35;     % wheel speed threshold (counts/s) for running classification
minDuration  = 0.2;    % min running bout duration (s) to classify a trial as running

% FIR windowing parameters
% stim_duration is auto-detected per session from PDI.stimInfo (see session loop).
time_window_after_offset = 12;     % post-stimulus window to model (seconds)
time_resampling          = 1;    % node/bin spacing (seconds) — default 0.5 s
basis_type               = 'tent'; % 'tent' (default) or 'boxcar'

% HRF kernel still needed for runningFrameMask computation (build_wheel_signal)
hrfParams    = [2.4  8  0.8  0.9  6  0  16];


%% =========================================================================
%  LOAD DATASET PATHS  (via the local Datapath.m)
%  =========================================================================

[subDataPath, subAnatPath, ~] = fonduta.io.datapath.Datapath('VisualTest');
resultPath = '/data06/fUSIMethodsPaper/Data_analysis/LC';

fprintf('\n=================================================\n');
fprintf(' analysis_visual_FONDUTA_FIR.m  |  condition: %s\n', condition);
fprintf(' FIR basis : %s\n', basis_type);
fprintf(' Post-stim window: %g s  |  time_resampling: %g s/node\n', ...
    time_window_after_offset, time_resampling);
fprintf(' stim_duration: auto-detected per session from PDI.stimInfo\n');
fprintf(' Sessions found: %d\n\n', numel(subDataPath));
fprintf(' Results will be saved in:\n\n %s\n', fullfile(resultPath, resultFolder));
fprintf('=================================================\n\n');


%% =========================================================================
%  MAIN SESSION LOOP
%  =========================================================================

warning('off', 'all');
sesIncl = [];

% Load the atlas (always useful)
atlas = fonduta.atlas.load_atlas();

for isub = 1:numel(subDataPath)

    fprintf('\n--- Session %d / %d ---\n', isub, numel(subDataPath));

    try

        % -----------------------------------------------------------------
        % 1. Load data
        % -----------------------------------------------------------------
        [PDI, anatomic, Transf] = fonduta.io.datapath.load_session( ...
            subDataPath{isub}, subAnatPath{isub});

        % -----------------------------------------------------------------
        % 2. Running trial detection & session inclusion check
        % -----------------------------------------------------------------
        [stationaryTrialIdx, runningTrialIdx] = fn.detect_running_trials( ...
            PDI, speedThresh, minDuration);

        if isempty(stationaryTrialIdx) || isempty(runningTrialIdx)
            continue
        end

        sesIncl = [sesIncl, isub]; %#ok<AGROW>

        % -----------------------------------------------------------------
        % 3. Brain masks
        % -----------------------------------------------------------------
        [bmask, nonBrainMask, allen_regions] = fonduta.atlas.build_slice_masks(anatomic, Transf);

        % -----------------------------------------------------------------
        % 4. TR and HRF kernel (HRF used only for runningFrameMask below)
        % -----------------------------------------------------------------
        TR         = mean(diff(PDI.time));
        hrf_kernel = fonduta.signal.hrf(TR, hrfParams);

        % -----------------------------------------------------------------
        % 4b. Auto-detect stimulus duration from PDI.stimInfo
        %     Computed per session (sessions may differ in stimulus timing).
        % -----------------------------------------------------------------
        stim_durations = PDI.stimInfo.endTime - PDI.stimInfo.startTime;
        stim_duration  = mean(stim_durations);
        fprintf('  Stim duration: %.2f s (mean over %d trials; range %.2f – %.2f s)\n', ...
            stim_duration, numel(stim_durations), min(stim_durations), max(stim_durations));

        % -----------------------------------------------------------------
        % 5. Build predictor signals
        % -----------------------------------------------------------------
        [stim_all, stim_stationary] = fn.build_visual_predictors( ...
            PDI, stationaryTrialIdx, runningTrialIdx);

        [wheel, wheelSmooth, runningFrameMask] = fn.build_wheel_signal( ...
            PDI, speedThresh, hrf_kernel);

        pc1Signals = fonduta.utils.extract_pc1_signals(PDI, bmask, nonBrainMask);

        globalPC1   = pc1Signals.globalPC1;
        nonBrainPC1 = pc1Signals.nonBrainPC1;

        % -----------------------------------------------------------------
        % 6. Pre-processing for continuous FIR predictors
        %    • Centre wheel speed before FIR expansion to preserve 0 baseline.
        %    • Compute interaction BEFORE FIR expansion, as a [T × 1] product.
        % -----------------------------------------------------------------
        wheel_c     = wheel - mean(wheel);          % centred wheel speed
        interaction = stim_all .* wheel_c;          % stimulus × centred speed

        % -----------------------------------------------------------------
        % 7. FIR operator
        %    fir(ev) expands any [T × 1] vector into [T × N] FIR basis columns.
        %    skip_zscore=true must be passed to fonduta.glm.ols for all FIR models.
        % -----------------------------------------------------------------
        fir = @(ev) fn.generate_fir_basis( ...
            ev, TR, stim_duration, time_window_after_offset, ...
            time_resampling, basis_type);

        % Verify N (already printed above; recompute per session in case TR varies)
        N_check = size(fir(stim_all), 2);
        fprintf('  FIR basis: N = %d nodes per predictor\n', N_check);

        % -----------------------------------------------------------------
        % 8. Fit FIR GLM models
        %
        %    fonduta.glm.ols(name, PDI3D, bmask, X, labels, contrasts, skip_zscore)
        %    skip_zscore = true  (do NOT z-score FIR columns)
        %
        %    Contrast matrices C have shape [N × (p+1)], where p is the total
        %    number of predictor columns in X (intercept excluded) and the last
        %    column of C is always 0 (the intercept).
        % -----------------------------------------------------------------

        all_results = struct();

        %% --- F1: Stimulus only (FIR basis, all trials) ---
        fprintf('  F1: Stimulus only (FIR) : M1_StimOnly\n');
        B_stim = fir(stim_all);     % [T × N]
        p_F1   = N_check;           % N predictor columns

        % Contrast: test all N stim_fir columns jointly
        % Xfull = [B_stim | intercept] → (p_F1 + 1) columns
        C_F1_stim         = zeros(N_check, p_F1 + 1);
        C_F1_stim(:, 1:N_check) = eye(N_check);

        contrast_F1(1).name = 'Visual_FIR';
        contrast_F1(1).C    = C_F1_stim;

        labels_F1 = arrayfun(@(k) sprintf('stim_fir_%02d', k), 1:N_check, ...
                              'UniformOutput', false);

        all_results.F1_StimOnly = fonduta.glm.ols( ...
            'F1_StimOnly', PDI.PDI, bmask, ...
            B_stim, labels_F1, contrast_F1, true);

        %% --- F2: Behavior (stimulus + wheel + interaction, all as FIR) ---
        fprintf('  F2: Behavior (FIR) : M5_Behavior\n');
        B_wheel = fir(wheel_c);      % [T × N]
        B_inter = fir(interaction);  % [T × N]

        % Full design: [B_stim | wheel_c_raw | B_wheel | B_inter]
        % Column ranges in Xfull (1-indexed, intercept is last = col 3N+2):
        %   stim cols  : 1 .. N
        %   wheel_raw  : N+1
        %   wheel cols : N+2 .. 2N+1
        %   inter cols : 2N+2 .. 3N+1
        %   intercept  : 3N+2
        p_F2 = 3*N_check + 1;   % total predictors (excl. intercept)
        ncols_Xfull_F2 = p_F2 + 1;

        C_F2_stim  = zeros(N_check, ncols_Xfull_F2);
        C_F2_stim(:, 1:N_check) = eye(N_check);

        C_F2_wheel = zeros(N_check, ncols_Xfull_F2);
        C_F2_wheel(:, (N_check+2):(2*N_check+1)) = eye(N_check);

        C_F2_inter = zeros(N_check, ncols_Xfull_F2);
        C_F2_inter(:, (2*N_check+2):(3*N_check+1)) = eye(N_check);

        contrast_F2(1).name = 'Visual_FIR';       contrast_F2(1).C = C_F2_stim;
        contrast_F2(2).name = 'Wheel_FIR';         contrast_F2(2).C = C_F2_wheel;
        contrast_F2(3).name = 'Interaction_FIR';   contrast_F2(3).C = C_F2_inter;

        labels_stim  = arrayfun(@(k) sprintf('stim_fir_%02d',  k), 1:N_check, 'UniformOutput', false);
        labels_wheel = arrayfun(@(k) sprintf('wheel_fir_%02d', k), 1:N_check, 'UniformOutput', false);
        labels_inter = arrayfun(@(k) sprintf('inter_fir_%02d', k), 1:N_check, 'UniformOutput', false);
        labels_F2    = [labels_stim, {'wheel_raw'}, labels_wheel, labels_inter];

        X_F2 = [B_stim, wheel_c, B_wheel, B_inter];
        
        all_results.F2_Behavior = fonduta.glm.ols( ...
            'F2_Behavior', PDI.PDI, bmask, ...
            X_F2, labels_F2, contrast_F2, true);
            
        %% --- F3: Stationary visual (FIR on stationary frames only) ---
        %   Mirrors M8_SteadyVisual: fit only on frames uncontaminated by running.
        fprintf('  F3: Stationary visual (FIR) : M8_SteadyVisual\n');
        stationaryFrames = ~runningFrameMask(:);
        PDI_steady       = PDI.PDI(:, :, stationaryFrames);

        % Build FIR basis on the stationary subset of stim_stationary
        B_stim_steady = fir(stim_stationary(stationaryFrames));

        p_F3 = N_check;
        C_F3_stim         = zeros(N_check, p_F3 + 1);
        C_F3_stim(:, 1:N_check) = eye(N_check);

        contrast_F3(1).name = 'Visual_Steady_FIR';
        contrast_F3(1).C    = C_F3_stim;

        labels_F3 = arrayfun(@(k) sprintf('stim_steady_fir_%02d', k), 1:N_check, ...
                              'UniformOutput', false);
        
        all_results.F3_SteadyVisual = fonduta.glm.ols( ...
            'F3_SteadyVisual', PDI_steady, bmask, ...
            B_stim_steady, labels_F3, contrast_F3, true);

        disp('Done fitting FIR models')
        
        % -----------------------------------------------------------------
        % 9. Assemble glmresult
        % -----------------------------------------------------------------
        glmresult             = struct();
        glmresult.dataPath    = subDataPath{isub};
        glmresult.anatPath    = subAnatPath{isub};
        glmresult.Transf      = Transf;
        glmresult.bmask       = bmask;
        glmresult.nonBrainMask  = nonBrainMask;
        glmresult.allen_regions = allen_regions;

        % Raw predictor time-series (same as HRF script for downstream compatibility)
        glmresult.predictors.stim_all          = stim_all;
        glmresult.predictors.stim_stationary   = stim_stationary;
        glmresult.predictors.wheel             = wheel;
        glmresult.predictors.wheel_centered    = wheel_c;
        glmresult.predictors.wheelSmooth       = wheelSmooth;
        glmresult.predictors.interaction       = interaction;
        glmresult.predictors.runningFrameMask  = runningFrameMask;
        glmresult.predictors.globalPC1         = globalPC1;
        glmresult.predictors.nonBrainPC1       = nonBrainPC1;
        glmresult.predictors.stationaryTrialIdx = stationaryTrialIdx;
        glmresult.predictors.runningTrialIdx   = runningTrialIdx;

        % FIR parameters (stored at top level for reference)
        glmresult.fir_params.stim_duration            = stim_duration;
        glmresult.fir_params.time_window_after_offset = time_window_after_offset;
        glmresult.fir_params.time_resampling          = time_resampling;
        glmresult.fir_params.basis_type               = basis_type;
        glmresult.fir_params.N_nodes                  = N_check;
        glmresult.fir_params.TR                       = TR;

        % Model results
        glmresult.models = all_results;

        % -----------------------------------------------------------------
        % 10. Save session result as glm_<runName>_FIR.mat
        %     (uses parsave directly to append _FIR suffix to the filename)
        % -----------------------------------------------------------------
        parts   = strsplit(subDataPath{isub}, '/');
        parts   = parts(~cellfun(@isempty, parts));
        runName = parts{end};

        outDir   = fullfile(resultPath, resultFolder);
        saveName = fullfile(outDir, sprintf('FIR_glm_%s.mat', runName));

        if ~exist(outDir, 'dir')
            mkdir(outDir);
        end

        data = glmresult;   % variable must be named 'data' for load compatibility
        save(saveName, 'data');
        fprintf('Saved: %s\n', saveName);

    catch ME
        fprintf('ERROR in session %d: %s\n', isub, ME.message);
        fprintf('  File: %s  Line: %d\n', ME.stack(1).file, ME.stack(1).line);
        fprintf('Skipping session %d.\n', isub);
    end

end



fprintf('\n=================================================\n');
fprintf(' Included sessions (%d / %d):\n', numel(sesIncl), numel(subDataPath));
disp(sesIncl);
fprintf('=================================================\n');
