%% Analyses for revision

% The reviewer poses suggests that our procedure of carrying out GLM using
% the canonical HRF (from Nunez-Elizalde) might be too simplistic and not
% capture the variability of the HRF across regions and stimuli, which in
% turn would yield a suboptimal advantage when using the motion as an 
% (hrf-convolved) regressors to explain out the effect of motion.
% 
% The reviewer's advice is to test whether estimating the effect using
% time-shifted delta functions would help separate motion from the actual
% effect of the stimulus. In the simplest version, this leads to a FIR
% analysis. One way of assessing whether the FIR brings any advantage with 
% respect to the HRF is to compare the eta2 maps generated by either the
% canonical HRF or by the FIR. We will carry out this using the same method
% of 2D correlation used for our main result.
%
% At the same time, this gives us also an opportunity to assess whether the 
% canonical HRF represents an efficient approximation to the actual HRF. 
% For this, we cannot use the HRF recovered by FIR, since the amount of 
% hrf-convolved predictors is quite high (at most 30 for each one), which
% can lead to inaccurate beta values - when the aim is to reconstruct the
% HRF. Therefore in this case we will use ridge regression with LOO cross-
% validation, where the lambda optimization parameter is estimated from the
% testing portion of the trials.

%% Initialization

% Import the package
FONDUTA_PATH = '/data00/leonardo/github/fUSI_analyses/FONDUTA';
addpath(genpath(FONDUTA_PATH));

% Add path with the functions for this analysis
addpath(genpath('.'));

% Load the atlas
atlas = fonduta.atlas.load_atlas();

% Load to get the location of anatomic and transformation
[datapaths, anatpaths, ~] = fonduta.io.datapath.Datapath('VisualTest');

% Location of the glm results
% NB: in the following, HRF_glm_files refers to the results of the glm
% using the canonical HRF.
glm_results_path = '/data06/fUSIMethodsPaper/Data_analysis/LC/VisualTest';
HRF_glm_files = dir(fullfile(glm_results_path, 'glm*.mat'));

% Define models
models = struct( ...
    'name', {'M8_SteadyVisual', 'M5_Behavior', 'M1_StimOnly'}, ...
    'predictor', {'stim_stationary_hrf', 'stim_hrf', 'stim_hrf'});


%% Eta2 mean and frequency maps in allen space
%  Inspect the results with fonduta.viz.view_atlas

eta2_mean_results_path = fullfile(pwd, 'HRF_analysis_revision', 'eta2_mean_maps');
mkdir(eta2_mean_results_path);

eta2 = calculate_mean_eta2_maps(HRF_glm_files, ...
    datapaths, ...
    anatpaths, ...
    atlas, ...
    models, ...
    eta2_mean_results_path);


%% Extract average peristimulus HRF for M8 (stationary) and M1 (all Stims)
%  NB: DO NOT evaluate all this cell at once. Follow the instructions.

hrf_analysis_path = fullfile(pwd, 'HRF_analysis_revision', 'results_simple_average');

% 0. Extract and save the average peristimulus time courses.
%    Skip(ped) if alredy calculated
opts.resultPath = hrf_analysis_path;
opts.eta2_thresh_val = 0.03;

%    Choose one
opts.model = 'M8_SteadyVisual';
% opts.model = 'M1_StimOnly';

analysis_simple_average(glm_results_path,opts);



% Viewing the correlation with the HRF and plotting the avg time courses:

% 1. First print the table of the correlation for all (suprathreshold) regions
% NB: You might need to lower the opts.sim_thresh.
opts.sim_thresh       = 0.5;   % only show regions where corr with canonical hrf is >= than this
opts.n_subject_thresh = 10;     % only show regions present in >= this many subjects
opts.smooth_win_s     = 5;     % moving-average smoothing window in seconds (0 = off)

analysis_simple_average_view_results.view_table(opts)


% 2. Then choose one region from the table to see the plot.
%    Optionally, (re)set the running window average
opts.target_acr   = 'LGd-co';    % Allen acronym — pick from Part 2 table
opts.smooth_win_s = 5;         % seconds (0 = off)

analysis_simple_average_view_results.plot_similarity(opts)


% 3. Generate a map to inspect with fonduta.viz.view_atlas
opts.sim_thresh       = 0;
opts.smooth_win_s     = 5;
opts.statistic        = 'mean';

analysis_simple_average_generate_allen_map(opts);

% 4. View the map
fonduta.viz.view_atlas








