%% Analyses for revision

% The reviewer suggests that our procedure of carrying out GLM using
% the canonical HRF (from Nunez-Elizalde) might be too simplistic and not
% capture the variability of the HRF across regions and stimuli, which in
% turn would yield a suboptimal advantage when using the motion as an 
% (hrf-convolved) regressors to explain out the effect of motion.
% 
% The reviewer's advice is to test whether estimating the effect using
% time-shifted delta functions would help separate motion from the actual
% effect of the stimulus. In the simplest version, this leads to a FIR
% analysis. One way of assessing whether the FIR brings any advantage with 
% respect to the HRF is to compare the eta2 maps generated by either the
% canonical HRF or by the FIR. We will carry out this using the same method
% of 2D correlation used for our main result.
%
% At the same time, this gives us also an opportunity to assess whether the 
% canonical HRF represents an efficient approximation to the actual HRF. 
% For this, we cannot use the HRF recovered by FIR, since the amount of 
% hrf-convolved predictors is quite high (at most 30 for each one), which
% can lead to inaccurate beta values - when the aim is to reconstruct the
% HRF. Therefore in this case we will use ridge regression with LOO cross-
% validation, where the lambda optimization parameter is estimated from the
% testing portion of the trials.


%% ========================================================================
%  INITIALIZATION & PATH SETUP
%  ========================================================================

% Add external packages and local analysis functions
FONDUTA_PATH = '/data00/leonardo/github/fUSI_analyses/FONDUTA';
addpath(genpath(FONDUTA_PATH));
addpath(genpath('.'));

% Load reference atlas
atlas = fonduta.atlas.load_atlas();

% Data & GLM directory paths
glm_results_path = '/data06/fUSIMethodsPaper/Data_analysis/LC/VisualTest';

% Load dataset filepaths
[datapaths, anatpaths, ~] = fonduta.io.datapath.Datapath('VisualTest');

% Extract run numbers from datapaths (vectorized)
run_names   = cellfun(@(p) fileparts(p(1:end-1)), datapaths, 'UniformOutput', false);
run_numbers = extractAfter(run_names, 'run-');

% Locate GLM result files
HRF_glm_files = dir(fullfile(glm_results_path, 'glm*.mat'));
FIR_glm_files = dir(fullfile(glm_results_path, 'FIR_glm*.mat'));

% Define the models 

% Canonical HRF Models
hrf_models = struct( ...
    'prefix',    {'HRF',         'HRF',                 'HRF'}, ...
    'name',      {'M1_StimOnly', 'M8_SteadyVisual',     'M5_Behavior'}, ...
    'predictor', {'stim_hrf',    'stim_stationary_hrf', 'stim_hrf'} ...
);

% Finite Impulse Response (FIR) Models
fir_models = struct( ...
    'prefix',    {'FIR',         'FIR',               'FIR',         'FIR'}, ...
    'name',      {'M1_StimOnly', 'M8_SteadyVisual',   'M5_Behavior', 'M5_Behavior'}, ...
    'predictor', {'Visual_FIR',  'Visual_Steady_FIR', 'Visual_FIR',  'Wheel_FIR'} ...
);

%% Similarity of eta2 with canonical HRF or FIR glm
% In this part we tackle the crucial question of whether the signal is
% modelled more appropriately using FIR (time-shifted delta functions) than
% with the canonical HRF. 
% The calculation of the maps has already been carried out in the
% analysis_visual_FONDUTA_[FIR/HRF], and here we compare the results using
% a simple method: the correlation of the eta2 maps from either GLMs.

% IMPORTANT: HRF vs FIR eta2 map correspondence
%
% Both HRF and FIR analyses now use identical model names (M1_StimOnly, 
% M5_Behavior, M8_SteadyVisual).
%
% We are interested only in models M1, M5, and M8:
%
%   HRF                         FIR
%   M1_StimOnly                 M1_StimOnly
%   M5_Behavior                 M5_Behavior
%   M8_SteadyVisual             M8_SteadyVisual
%
% For M1_StimOnly and M8_SteadyVisual, there is only one relevant predictor 
% (apart from the intercept), so the correspondence is straightforward:
%
%   HRF eta2(1,:,:)             FIR fcontrasts.<Visual_FIR/Visual_Steady_FIR>.eta2_p
%
% For M5_Behavior, the HRF model contains four non-intercept predictors,
% while the FIR model stores the relevant effects as named F-contrasts.
% The correspondence is:
%
%   HRF models.M5_Behavior        | FIR models.M5_Behavior
%   ------------------------------|----------------------------------------
%   eta2(1,:,:)                   | fcontrasts.Visual_FIR.eta2_p
%   eta2(3,:,:)                   | fcontrasts.Wheel_FIR.eta2_p
%   eta2(4,:,:)                   | fcontrasts.Interaction_FIR.eta2_p

% Note that the HRF eta2(2,:,:) map is intentionally NOT used. The
% relevant HRF predictors for M5 are therefore indices 1, 3, and 4.
%
% The brain mask is subject-specific, but is identical between the HRF
% and FIR results for a given subject. Therefore, for each subject we use
% that subject's HRF bmask to select voxels from both eta2 maps before
% calculating their spatial correlation.
%
% The HRF and FIR eta2 maps have the same spatial dimensions (158 x 90).


%% ========================================================================
%  ETA2 MEAN MAPS & SPATIAL CORRELATIONS IN ALLEN SPACE
%  ========================================================================

eta2_mean_results_path = fullfile(pwd, 'HRF_analysis_revision', 'eta2_mean_maps');

% Calculate/load HRF & FIR mean eta2 maps
hrf_eta2 = calculate_mean_eta2_maps(HRF_glm_files, datapaths, anatpaths, atlas, hrf_models, eta2_mean_results_path, 'normalize', true);
fir_eta2 = calculate_mean_eta2_maps(FIR_glm_files, datapaths, anatpaths, atlas, fir_models, eta2_mean_results_path, 'normalize', true);

% Print Spatial Correlation across models
allsubs_mask = fir_eta2.FIR_M1_StimOnly_Visual_FIR_norm.mask;

comparisons = {
    'M5_Behavior',        'HRF_M5_Behavior_stim_hrf_norm',        'FIR_M5_Behavior_Visual_FIR_norm';
    'M1_AllStims',         'HRF_M1_StimOnly_stim_hrf_norm',        'FIR_M1_StimOnly_Visual_FIR_norm';
    'M8_StationaryStims', 'HRF_M8_SteadyVisual_stim_stationary_hrf_norm', 'FIR_M8_SteadyVisual_Visual_Steady_FIR_norm'
};

for i = 1:size(comparisons, 1)
    fprintf('\n')
    modelName = comparisons{i, 1};
    hrfMap    = hrf_eta2.(comparisons{i, 2}).mean;
    firMap    = fir_eta2.(comparisons{i, 3}).mean;
    
    valid_vox = (allsubs_mask > 0) & ~isnan(hrfMap) & ~isnan(firMap);
    r = corr(hrfMap(valid_vox), firMap(valid_vox));
    
    fprintf('Spatial correlation of %s group-level avg map in allen space: r = %.4f\n\n', modelName, r);
end


%% ========================================================================
%  SUBJECT-LEVEL HRF vs FIR SPATIAL CORRELATION ANALYSIS
%  ========================================================================

corr_results_path = fullfile(pwd, 'HRF_analysis_revision', 'subject_level_similarities');

% Compute or load saved correlation structs
res_M1 = eta2_HRF_FIR_correlation(HRF_glm_files, FIR_glm_files, 'M1_StimOnly', corr_results_path);
res_M8 = eta2_HRF_FIR_correlation(HRF_glm_files, FIR_glm_files, 'M8_SteadyVisual', corr_results_path);
res_M5 = eta2_HRF_FIR_correlation(HRF_glm_files, FIR_glm_files, 'M5_Behavior', corr_results_path);

% Generate figures and statistics
plot_subject_level_similarity(res_M1, res_M5, res_M8, HRF_glm_files);


%% ========================================================================
%  SINGLE-SUBJECT HRF vs FIR ETA2 MAP VISUAL COMPARISON
%  ========================================================================
%  Visualizes a single representative subject to evaluate spatial patterns 
%  independently of inter-subject amplitude variations or registration overlap.
%  Since the overlap of the blades is not perfect, and there are big
%  differences in the eta2 across subjects, the visualization of the mean
%  eta2 in allen space is not optimal.
%  The viz of a single representative subject is better.
%  Because of the differences in eta2 between hrf and fir glm, we normalize
%  the values in the range 0..1 since we are actually most interested in
%  the pattern rather than the specific values.

glm_results_path = '/data06/fUSIMethodsPaper/Data_analysis/LC/VisualTest';

run_num = '115826';
run_num = '112118';
% run_num = '152916';
% run_num = '104841';
% run_num = '154343';
% run_num = '152201';
% run_num = '122011';
% run_num = '101347';
% run_num = '142450';
run_num = '142742';
% 
% run_num = run_numbers{32};


model = 'M5_Behavior';
normalize = true;

compare_hrf_fir_eta2(glm_results_path, run_num, model, normalize);




%% Extract average peristimulus HRF for M8 (stationary) and M1 (all Stims)
%  NB: DO NOT evaluate all this cell at once. Follow the instructions.

% Here we tackle in the simplest way the question of whether the canonical
% HRF is appropriate to model the haemodynamic response to the stimuli: we
% simply plot the average peristimulus time course and we compare it (using
% correlation or cosine similarity) with the boxcar convolved with the
% canonical HRF.
% One interesting thing to do is to visualize the shape of the average hrf
% in regions with large eta2 wrt regions which are not "activated" by the
% stimulus.

hrf_analysis_path = fullfile(pwd, 'HRF_analysis_revision', 'results_simple_average');
opts.resultPath = hrf_analysis_path;

% Extract and save the average peristimulus time courses.
% - For regions with at least N min_active_voxes at the given eta2 threshold,
%   only those voxels are selected to calculate the average time course.
% - For all other regions, the voxels with the top 5% eta2 values are selected
%   for the average time course.

opts.eta2_thresh_val = 0.03;
opts.min_active_voxels = 5;

% Choose one model among M1, M5, M8
% Note that we are _not_ modelling here. M8 is to isolate the peristimulus
% time course in stationary trials. M1 considers all trials.
%
% For models with nuisance parameters (like M5), choose also the labels of
% the nuisance predictors.

% opts.model = 'M8_SteadyVisual';
% opts.model = 'M1_StimOnly';

opts.model           = 'M5_Behavior';
opts.nuisance_labels = {'wheel', 'wheel_hrf', 'interaction_hrf'};

analysis_simple_average(glm_results_path,opts);

% tic
% analysis_simple_average_parallel(glm_results_path,opts);
% toc

% -------------------------------------------------------------------------

% Viewing the correlation with the HRF and plotting the avg time courses:

% 0. You can use this modification of the fonduta.viz.view_atlas.
view_simple_average_results()

% If you want to generate the single components, use the code below

% % 1. First print the table of the correlation for all (suprathreshold) regions
% % NB: You might need to lower the opts.sim_thresh.
% opts.sim_thresh       = 0.85;   % only show regions where corr with canonical hrf is >= than this
% opts.n_subject_thresh = 10;     % only show regions present in >= this many subjects
% opts.smooth_win_s     = 5;     % moving-average smoothing window in seconds (0 = off)
% 
% analysis_simple_average_view_results.view_table(opts)
% % -------------------------------------------------------------------------
% 
% 
% 
% % 2. Then choose one region from the table to see the plot.
% %    Optionally, (re)set the running window average
% opts.target_acr   = 'LGv';    % Allen acronym — pick from Part 2 table
% opts.smooth_win_s = 5;         % seconds (0 = off)
% 
% analysis_simple_average_view_results.plot_similarity(opts)
% % -------------------------------------------------------------------------
% 
% 
% % 3. Generate a map to inspect with fonduta.viz.view_atlas
% opts.sim_thresh       = 0;
% opts.smooth_win_s     = 5;
% opts.statistic        = 'mean';
% 
% analysis_simple_average_generate_allen_map(opts);
% 
% % view the map
% fonduta.viz.view_atlas


% Additionally, we can see in which regions the effect of denoising using
% the convolved motion + interaction(motion*stimuli) was most evident

res_dir = fullfile(pwd, 'HRF_analysis_revision','results_simple_average')

M1 = load(fullfile(res_dir, "simple_avg_M1_StimOnly_eta003_map.mat"));
M5 = load(fullfile(res_dir, "simple_avg_M5_Behavior_eta003_map.mat"));

M5_minus_M1 = M5.correlation_map - M1.correlation_map;
save(fullfile(res_dir,'M5_minus_M1.mat'),'M5_minus_M1');

M1_minus_M5 = M1.correlation_map - M5.correlation_map;
save(fullfile(res_dir,'M1_minus_M5.mat'),'M1_minus_M5');

% fonduta.viz.view_atlas








